name: deploy-react-project

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: "Get repository code"
        uses: actions/checkout@v4

      - name: "Cache dependeicnes"
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: "Installing dependencies"
        run: npm install

      - name: "Test Application"
        run: npm run test

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: "Get repository code"
        uses: actions/checkout@v4

      - name: "Cache dependeicnes"
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: "Installing dependencies"
        run: npm install

      - name: "Lint Application"
        run: npm run lint

  build:
    needs: [lint, test]
    continue-on-error: true
    strategy:
      matrix:
        node-version: [14, 17]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Get repository code"
        uses: actions/checkout@v4

      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Cache dependeicnes"
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: "Installing dependencies"
        run: npm install

      - name: "Building Application"
        run: npm run build

      - name: "Deploying application"
        run: echo "Deploying..."
