name: deploy-react-project

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: "Get repository code"
        uses: actions/checkout@v4

      - name: "Cache dependeicnes"
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: "Installing dependencies"
        run: npm install

      - name: "Test Application"
        run: npm run test

  lint:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: "Get repository code"
        uses: actions/checkout@v4

      - name: "Cache dependeicnes"
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: "Installing dependencies"
        run: npm install

      - name: "Lint Application"
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: "Get repository code"
        uses: actions/checkout@v4

      - name: "Cache dependeicnes"
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: "Installing dependencies"
        run: npm install

      - name: "Building Application"
        run: npm run build

      - name: "Deploying application"
        run: echo "Deploying..."
